### ISSUE TITLE
Bump 'statsd-ruby' dependency?

### ISSUE THREAD

**Issue by findchris** [tsnow/em-statsd#2]
Looks like the `gemspec` requires 
```ruby
'statsd-ruby', "~>0.2"
```

That gem is currently on `v1.2`.  Can you bump this dependency version?  Lots of fixes since `0.2`.

**Comment by findchris** [comment]
Any chance of this getting a version bump?

**Comment by tsnow** [comment]
Version 1.0.0 available now on Rubygems.org: https://rubygems.org/gems/em-statsd

Sorry for the slow turnaround and radio silence.

Best,

@tsnow

**Comment by findchris** [comment]
Excellent, thanks :+1:
